Initial commit
codice/openddms pull request #1
Opened 2018-08-03 18:18 UTC by AzGoalie

#### What does this PR do?
Initial commit of openddms.
#### Who is reviewing it? 
@coyotesqrl @bakejeyner @ahoffer @brendan-hofmann @andrewkfiedler @gordocanchola @brjeter

2018-08-03 20:54 UTC, mackncheesiest reviewed
Asking the hard questions 😄

2018-08-03 20:54 UTC, mackncheesiest commented on src/main/kotlin/org/codice/ddms/gml/v3/SrsAttributes.kt
> +        val sb = StringBuffer()
❓ Any reason for `StringBuffer` here and `StringBuilder` [here](https://github.com/codice/openddms/pull/1/files#diff-d84138f8416732a12307b29fef846e2dR21)?

2018-08-03 21:00 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/gml/v3/SrsAttributes.kt
> +        val sb = StringBuffer()
Nope, good catch 👍

2018-08-29 22:36 UTC, coyotesqrl commented on build.gradle.kts
> +    kotlin("jvm") version "1.2.60"
✏️ Should bump to latest, `1.2.61` as of this review.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/DateFormat.kt
> +            DateTimeFormatter.ISO_LOCAL_DATE,                   // yyy-MM-dd
✏️ The comment should be `yyyy-MM-dd`.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/DateFormat.kt
> +        for (formatter in formatters) {
✏️ This is potentially very inefficient/expensive (depending on how common any of the date formats other that ISO_OFFSET are. Since the four formats this accepts are of distinct sizes, it might be better to check the length of the input `date` and select the one formatter that _might_ be able to interpret the value. If that one can't, then you can catch/ignore and return false.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/DateFormat.kt
> +    fun parse(date: String): Date? {
✏️ Similar inefficiency here. If you extract some of the logic from `isValid` (excluding the allowance for `unknownOrNotApplicable` values) you can create a simple `getParser` private method that returns a small data object containing the parser that knows how to convert to date. In the above method, a return value of `null` would mean you can't parse and you can return `false`. In this method, you can just return the Date off of that decorated instance.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/Position.kt
> +        val sb = StringBuilder()
✏️ More Kotlin-y (and a bit easier to read):
```kotlin
        return """<gml:pos $srsAttributes xmlns:gml="http://www.opengis.net/gml">
            |${points.joinToString(" ")}
            |"</gml:pos>
        """.trimMargin().replace("\n", "")
```

(Double check that the output is what you want it to be, of course. The `\n` replacement is annoying, but putting it all on one line would be too long.)

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/SrsAttributes.kt
> +    override fun toString(): String {
✏️ Note that with the current implementation, you're inserting a blank space before everything but `srsName`, even if there is no `srsName`. A comparable, slightly more functional version of this would be...
```kotlin
    private fun srsNameToString(): String {
        return if (srsName.isNotBlank()) """srsName="$srsName"""
        else ""
    }

    private fun srsDimensionToString(): String {
        return if (srsDimension > 0) """srsDimension=$srsDimension"""
        else ""
    }

    private fun axisLabelsToString(): String {
        return if (axisLabels.any(String::isNotBlank))
            """axisLabels="${axisLabels.joinToString(" ")}""""
        else ""
    }

    private fun uomLabelsToString(): String {
        return if (uomLabels.any(String::isNotBlank))
            """uomLabels="${uomLabels.joinToString(" ")}""""
        else ""
    }

    override fun toString(): String {
        return """
            |${srsNameToString()}
            | ${srsDimensionToString()}
            | ${axisLabelsToString()}
            | ${uomLabelsToString()}
        """.trimMargin().replace("\n", " ")
    }
```

I don't think, in this case, the raw string + functions is better, but it is a bit more testable.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/LinearRingBuilder.kt
> +fun linearRing(init: LinearRingBuilder.() -> Unit) =
✏️ As a personal preference, I don't like to pollute the global namespace too much. Would suggest moving `linearRing` (and similarly with all the other functions supporting the DSL) into companion object of class. Then consumers would just invoke `LinearRingBuilder.linearRing()` or an import could be added for `import org.codice.ddms.gml.v3.builder.LinearRingBuilder.Companion.linearRing`

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/PolygonBuilder.kt
> +    private lateinit var id: String
❓ I see that in `PointBuilder`, `id` is being initialized to an empty string instead of being lateinit. Is there a reason they're treated differently?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/PositionBuilder.kt
> +    fun points(vararg point: Double): PositionBuilder {
❓ Don't these doubles need to be a pair to represent a point? If so, should enforce that through the signature or at least with a `require` check.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/PositionBuilder.kt
> +    fun points(point: List<Double>): PositionBuilder {
❓ Same here: don't these doubles need to come in pairs?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/SrsAttributesBuilder.kt
> +        this.srsDimension = srsDimension
❓ Are there any restrictions on dimensions? Min/max size?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/SrsAttributesBuilder.kt
> +        axisLabels.addAll(axisLabel)
❓ Are there any restrictions on the labels? Blank/null values?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/Ddms20Resource.kt
> +        require(identifiers.isNotEmpty()) {
✏️ Should this instead confirm that there is at least one, non-blank identifier?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/Ddms20Resource.kt
> +        require(titles.isNotEmpty()) {
✏️ Should this instead confirm that there is at least one, non-blank title?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/Ddms20Resource.kt
> +        require(creators.isNotEmpty() || publishers.isNotEmpty() ||
✏️ Similar question here, where instead of only checking that at least one of the lists has an entry, we confirm that at least one of the lists contains a non-blank entry?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/ContactBuilder.kt
> +    fun person(init: PersonBuilder.() -> Unit): ContactBuilder {
❓ Function should be an overload of the `producer` name, yes?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/ContactBuilder.kt
> +    fun organization(init: OrganizationBuilder.() -> Unit): ContactBuilder {
I see the structure now, where `producer` is being set to a producer, person, organization, or service as appropriate. Not sure whether it's better to have the functions all named as they are now or to overload the `producer` function with the different value/builder inputs. I don't feel too strongly either way.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/Ddms20ResourceBuilder.kt
> +    private val identifiers: ArrayList<Identifier> = arrayListOf()
✏️ I haven't scrolled to confirm, but I suspect these fields are all ordered the same as in the `Ddms20Resource` in which case I understand the ordering but still don't love it. I think it would be easier for another engineer coming to this later to see all the fields ordered/grouped logically:
* all vals
* all vars
* all lateinit vars

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun geographicIdentifiers(vararg geographicIdentifier: GeographicIdentifier): GeospatialCoverageBuilder {
❓ Do you not want/need to support an overload that takes a `List<GeographicIdentifier>`? The other builders all have the `List` overloads when they have `vararg`.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun boundingBoxes(vararg boundingBox: BoundingBox): GeospatialCoverageBuilder {
❓ Same question about overloading with `List` flavor of fun.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun boundingBox(west: Double, east: Double, north: Double, south: Double) =
❓ Is this a usual/canonical ordering for the four compass points in ddms? Because it reads weird to me. I expect to see NSEW-ordered lists when there is no external ordering requirement.

❓ How do these four doubles define a box? Each point on a plane (or virtual plane) should require two coordinates to define it, not one. This seems to relate to my earlier question about points. Is there some translation in ddms that can determine a point from a single double?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun postalAddresses(vararg postalAddress: PostalAddress): GeospatialCoverageBuilder {
❓ Same question about List overload.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun verticalExtents(vararg verticalExtent: VerticalExtent): GeospatialCoverageBuilder {
❓ Same question about List overload.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/LinkBuilder.kt
> +    private lateinit var href: String
❓ Are the errors clear enough to the consumer of the api when they try to invoke the `build` method on one of the builders where the `lateinit` vars have not been set? Are they obtuse or can the user figure out what they've done wrong?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/SecurityAttributeBuilder.kt
> +        this.declassDate = declassDate
❓ Not a `Date`, either internally or as the parameter passed in? No need to overload to support that as input?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/SecurityAttributeBuilder.kt
> +    fun dateOfExemptedSource(dateOfExemptedSource: String): SecurityAttributeBuilder {
❓ Same question about operating on `Date` objects.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/geospatial/PostalAddressBuilder.kt
> +        streets.addAll(street)
❓ This hadn't occurred to me before now, but for all these builder methods that take varargs/lists, do you care how many times they are invoked by callers? Should you clear out the list on each invocation before adding the input contents?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/geospatial/PostalAddressBuilder.kt
> +    private var countryCode: CountryCode = CountryCode()
❓ Should this be `lateinit` instead? What is a "default"/empty `CountryCode`?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/producers/PersonBuilder.kt
> +    private val names: ArrayList<String> = arrayListOf()
❓ How do the multiple `names` relate to the singular `surname`?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/producers/ServiceBuilder.kt
> +    private val names: ArrayList<String> = arrayListOf()
❓ Any reason to deal with these three common fields this way instead of converting `ProducerBuilder` to an abstract class?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +                                    when (localName) {
✏️ These lambdas are nesting rather deeply. Can we flatten out a bit by extracting functions for the work, thereby keeping the overall logic at the same cognitive level within any given method?

It would also be nice to reduce the 109-line method down to something manageable and easy to read.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +            nextTag()
✏️ This second call to get the next tag is getting one of the coverage types? Can it be commented to make it clearer?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +                            nextTag() // WestBL
I guess this answers my earlier question about the canonical order of compass points in ddms. Very odd order.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +            while (localName != "relatedResources") {
❓ The case on the collection of related resources is camel-cased like above and on each contained `RelatedResource` is init-caps?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/resource/Title.kt
> +                "ddms:title and ddms:subtitle must contain a ism:classification"
✏️ S/b "...contain an ism:classification"

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/resource/Title.kt
> +            require(ownerProducer.isNotEmpty() && ownerProducer.any { it.isNotBlank() }) {
✏️ Can remove the first test.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/security/Security.kt
> +                "ddms:security must contain a ism:classification"
✏️ S/b "...contain an ism:classification"

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/security/Security.kt
> +            require(ownerProducer.isNotEmpty() && ownerProducer.any { it.isNotBlank() }) {
✏️ Can remove the first test.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/security/ism/Classification.kt
> +            return valueOf(value.replace("-", "_"))
❓ Do we not need to get the value of `No classification` back? Is that just reserved for missing values?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/security/ism/SecurityAttributeStrings.kt
> +    val classification = securityAttributes.classification
✏️ I think it would be easier to read if the fields that were directly copied over were in one group and those that were joined lists were then in a second group, perhaps with a blank line between them.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/summary/Description.kt
> +                "ddms:description must contain a ism:classification"
✏️ S/b "...contain an ism:classification"

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/summary/Description.kt
> +            require(ownerProducer.isNotEmpty() && ownerProducer.any { it.isNotBlank() }) {
✏️ Can remove the first test.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/summary/GeospatialCoverage.kt
> +        require(geographicIdentifiers.isNotEmpty() ||
✏️ I believe I asked a similar question w/r/t this class' builder: shouldn't the test in fact be that there is a valid, non-null entry in one of those lists?

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +    private val ddmsPrefix = "ddms"
✏️ Consts or vals in a companion object.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        ddms.description?.run {
✏️ It only matters in terms of a) consistency and b) return type, but I tend to prefer `apply` over `run`. It doesn't make a big difference, but SAML-CTK used `apply` over `run` if we want to shoot for Codice consistency.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        for (language in ddms.languages) {
✏️ Alternately: `ddms.languages.forEach {}`

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        ddms.dates?.run {
✏️ Same comment re: `apply` vs `run`.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        ddms.rights?.run {
✏️ Same comment re: `apply` vs `run`.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        for (source in ddms.sources) {
✏️ Alternately: `ddms.sources.forEach {}`

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        for (type in ddms.types) {
✏️ Alternately: `ddms.types.forEach {}`

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +    private fun writeOrganization(organization: Organization) {
✏️ Other than the wrapping `ddmsElement`, this method is identical to `writeService`. Could refactor to a single method that takes that element name and a `Producer`.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        ddms.format?.run {
✏️ Same comment re: apply vs run.

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        for (temporalCoverage in ddms.temporalCoverages) {
✏️ Alternately a foreach

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        for (virtualCoverage in ddms.virtualCoverages) {
✏️ Alternately a foreach

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +        for (geospatialCoverage in ddms.geospatialCoverages) {
✏️ Alternately a foreach

2018-08-29 22:36 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +                    RelatedResources.Direction.Outbound -> ddmsAttribute("direction", "outbound")
❓ Would it be better to have a `toString` or `toOutput` method of some such on the enum itself that could print out its name in lowercase? Then you could just have a single `ddmsAttribute("direction", relatedResources.direction.toOutput())` call here.

2018-08-29 22:36 UTC, coyotesqrl commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/PositionTest.kt
> +    fun `a Position create correct xml`() {
✏️ "creates"

2018-09-18 16:32 UTC, coyotesqrl commented
@bakejeyner, @ahoffer, @brendan-hofmann, @andrewkfiedler, @gordocanchola, and @brjeter

Tagging to remind you all that your reviews on this PR have been requested.

2018-10-06 21:34 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/gml/v3/Position.kt
> +        val sb = StringBuilder()
Done, but it's still a little funky because we need to account for when `srsAttributes` are empty else there would be a double space.

2018-10-06 22:26 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/PolygonBuilder.kt
> +    private lateinit var id: String
Nope, good catch

2018-10-06 22:42 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/PositionBuilder.kt
> +    fun points(vararg point: Double): PositionBuilder {
It changes based on the srsName, i don't think we should have an enforcement here even though the most common are pairs and trios of doubles.

2018-10-06 22:49 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/SrsAttributesBuilder.kt
> +        this.srsDimension = srsDimension
Just that it needs to be positive, added a require check to `SrsAttributes`

2018-10-06 22:53 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/gml/v3/builder/SrsAttributesBuilder.kt
> +        axisLabels.addAll(axisLabel)
We filter out empty values when we print. Could filter them out here when we add them but that doesn't stop someone from manually creating a `SrsAttributes` with empty strings.

2018-10-06 23:11 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/Ddms20Resource.kt
> +        require(identifiers.isNotEmpty()) {
Added validation to check for non blank values in Identifier

2018-10-06 23:12 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/Ddms20Resource.kt
> +        require(titles.isNotEmpty()) {
Added extra validation to check for non blank value in `Title`

2018-10-06 23:13 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/Ddms20Resource.kt
> +        require(creators.isNotEmpty() || publishers.isNotEmpty() ||
`Producers` has a requirement that there isn't a blank name, should cover this case.

2018-10-06 23:18 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/ContactBuilder.kt
> +    fun organization(init: OrganizationBuilder.() -> Unit): ContactBuilder {
I'm open to either option, going to leave it as is for now unless there's a compelling reason to change

2018-10-06 23:21 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/Ddms20ResourceBuilder.kt
> +    private val identifiers: ArrayList<Identifier> = arrayListOf()
I had them ordered to make it easier to confirm that i wasn't missing anything from the schemas. Now that there are proper tests, i can rearrange them.

2018-10-06 23:39 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun geographicIdentifiers(vararg geographicIdentifier: GeographicIdentifier): GeospatialCoverageBuilder {
Must have been an oversight, good catch

2018-10-06 23:40 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun boundingBoxes(vararg boundingBox: BoundingBox): GeospatialCoverageBuilder {
Must have been an oversight, good catch

2018-10-06 23:43 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun postalAddresses(vararg postalAddress: PostalAddress): GeospatialCoverageBuilder {
Must have been an oversight, good catch

2018-10-06 23:43 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun verticalExtents(vararg verticalExtent: VerticalExtent): GeospatialCoverageBuilder {
Must have been an oversight, good catch

2018-10-06 23:49 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/GeospatialCoverageBuilder.kt
> +    fun boundingBox(west: Double, east: Double, north: Double, south: Double) =
I can change the ordering, i forgot why i had it this way.
As for how this defines a box, it creates a box with with North / South being the northern and southern most Latitude values and East / West  being the eastern and western most Longitude values.

2018-10-07 07:56 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/LinkBuilder.kt
> +    private lateinit var href: String
The error returned is `kotlin.UninitializedPropertyAccessException: lateinit property href has not been initialized` which isn't vague, but also not the same as the other errors. I added a  check in `build`

2018-10-13 00:54 UTC, ahoffer approved these changes

2018-11-13 17:08 UTC, bakejeyner approved these changes

2019-02-01 00:30 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +            while (localName != "relatedResources") {
one of the oddities of DDMS 2.0. A singular `ReleatedResource` starts with a capital, while plural `relatedResources` is camel case

2019-02-04 19:32 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/SecurityAttributeBuilder.kt
> +        this.declassDate = declassDate
Changed to use new `DdmsDate` class.

2019-02-04 19:32 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/SecurityAttributeBuilder.kt
> +    fun dateOfExemptedSource(dateOfExemptedSource: String): SecurityAttributeBuilder {
Changed to use new `DdmsDate` class.

2019-02-04 19:44 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/geospatial/PostalAddressBuilder.kt
> +    private var countryCode: CountryCode = CountryCode()
The spec allows a 'blank' `CountryCode` object, but it could probably be more strict. The writer checks to see if the country code object is the 'default' and excludes it if so.

2019-02-04 19:44 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/geospatial/PostalAddressBuilder.kt
> +        streets.addAll(street)
I believe most builder objects like these don't clear the list. If we feel like it would make sense to, i can add it.

2019-02-04 19:48 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/producers/PersonBuilder.kt
> +    private val names: ArrayList<String> = arrayListOf()
According to the spec, it seems to be any name that's not the surname. First, Middle, and any other if necessary.

2019-02-04 21:36 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/producers/ServiceBuilder.kt
> +    private val names: ArrayList<String> = arrayListOf()
Moved, good catch.

2019-02-04 22:33 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/security/ism/Classification.kt
> +            return valueOf(value.replace("-", "_"))
It's reserved for missing values.

2019-02-04 22:36 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/summary/GeospatialCoverage.kt
> +        require(geographicIdentifiers.isNotEmpty() ||
That should be taken care of by each of the individual types. Can't create an invalid/empty list of these objects.

2019-02-05 00:08 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +                    RelatedResources.Direction.Outbound -> ddmsAttribute("direction", "outbound")
i like the `toString` method.

2019-02-06 19:04 UTC, AzGoalie commented
I had to suppress some detekt issues, they are all marked by `TODO` comments. Would like some input on them :)

2019-02-11 15:47 UTC, coyotesqrl approved these changes

2019-02-11 15:47 UTC, coyotesqrl commented on .gitattributes
> +# to native line endings on checkout.
❓ Should `*.kt` be added to this list?

2019-02-11 15:47 UTC, coyotesqrl commented on codice.license.kt
> +/**
✏️ Might want to consider the shorter license header we used for the [SAML-CTK](https://github.com/codice/saml-conformance/blob/master/codice.license.kt)

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/DdmsDate.kt
> +            parsedDate = datetimeFormatter.parse(date)
✏️ In the case of a date and not an unknown or N/A date, this ctor is going to attempt to parse it twice: once in the validation method and then again here. I don't have a great solution off the top of my head for this.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/DdmsDate.kt
> +        require(isValid(date)) {
✏️ Same problem with running the parse logic twice.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/DdmsDate.kt
> +        result = 31 * result + (parsedDate?.hashCode() ?: 0)
❗️ Your `equals` and `hashCode` methods are not equivalent, as this method includes the `parsedDate` in the generation of the hash code.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/SrsAttributes.kt
> +            "srsName=\"$srsName\""
✏️ Raw strings (triple-quoted) might read better than these escaped quote marks.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/gml/v3/SrsAttributes.kt
> +        return srsNameToString() +
✏️ Not sure I wouldn't use a string template for this instead of concatenation.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/producers/PersonBuilder.kt
> +        this.surname = surname
❓ Since this property is defined as `lateinit` and not pre-filled to an empty string, would it be reasonable to assume that empty string is not a valid value for it? In that case, shouldn't there be a validation check here?

This same question applies throughout the project where we have `lateinit` Strings.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/security/SecurityAttributeBuilder.kt
> +@Suppress("TooManyFunctions") // TODO: Not sure how we can make this 'smaller'
📓 I don't think you should bother trying to break it up. Any breakup here would be artificial. This is just a builder that has a lot of functions.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/builder/summary/GeospatialCoverageBuilder.kt
> +@Suppress("TooManyFunctions") // TODO: Not sure how we can make this 'smaller'
📓 Same. Let's just suppress and leave comments that the builders are building complex data objects and any breakup is artificial.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +                "Person" -> person {
I'm torn here. Part of me would prefer to see these builders extracted out to methods but I'm not sure that makes things more readable vs. less.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +    private fun <T : ProducerBuilder<T>> ProducerBuilder<T>.parseProducer(type: String) {
✏️ Might be best to move extension functions to their own section of this file.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +@Suppress("LargeClass", "TooManyFunctions") // TODO: Could break this up into logical parts to make this 'smaller'
✏️ One possibility here is to create classes to hold extension functions for each of the subtypes to be written, but those get a bit messy as you'd have to give them access to the common functions to do the actual writing, like `ddmsAttribute`, etc. I think it would make the structure harder to track and probably isn't worth the effort.

2019-02-11 15:47 UTC, coyotesqrl commented on src/main/kotlin/org/codice/ddms/xml/util/XmlUtils.kt
> +@Suppress("UnusedPrivateMember") // TODO: I think we should keep suppressing this one, or we could log it
✏️ I think just log this `documentedTag`.

2019-02-11 15:48 UTC, coyotesqrl requested changes
Oops. I accidentally approved when I meant to request changes for the hash code/equals incompatibility.

2019-02-12 21:03 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/gml/v3/SrsAttributes.kt
> +        return srsNameToString() +
I choose to use this instead because the methods contain a bunch of conditional logic.

2019-02-12 21:19 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/xml/util/XmlUtils.kt
> +@Suppress("UnusedPrivateMember") // TODO: I think we should keep suppressing this one, or we could log it
Moved it to `Ddms20XmlReader` and logged the argument.

2019-02-12 22:58 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/DdmsDate.kt
> +            parsedDate = datetimeFormatter.parse(date)
Fixed

2019-02-12 22:58 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/DdmsDate.kt
> +        require(isValid(date)) {
Fixed

2019-02-12 23:09 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/producers/PersonBuilder.kt
> +        this.surname = surname
The spec states that there must be a `surname` element, but it has no rules for if the value can be blank or not. I'm not sure which is better: Following the spec exactly or making this slightly more restrictive.

2019-02-12 23:14 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +                "Person" -> person {
I have no preference, but i moved them to be their own functions.

2019-02-12 23:15 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +@Suppress("LargeClass", "TooManyFunctions") // TODO: Could break this up into logical parts to make this 'smaller'
I'm just going to move the extension functions to be together like you suggested in your previous comment.

2019-02-12 23:23 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/writer/Ddms20XmlWriter.kt
> +@Suppress("LargeClass", "TooManyFunctions") // TODO: Could break this up into logical parts to make this 'smaller'
I was thinking of making multiple "readers" for each part of the ddms document. But that would only remove a few methods and make it harder to follow. For now i'm just going to move the extension functions to be together like your previous comment.

2019-02-14 17:08 UTC, bakejeyner approved these changes

2019-02-14 17:08 UTC, bakejeyner commented on src/main/kotlin/org/codice/ddms/v2/summary/TemporalCoverage.kt
> +)
❓ (Disclaimer: I know nothing about ddms) Would it be valuable to add an init block that requires the start date be  before the end date?

2019-02-14 17:08 UTC, bakejeyner commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +                if (datum.isNotBlank()) Datum.valueOf(datum) else null)
✏️ NitPick: Could also write these as ternaries:
```
                unit.isNotBlank() ? UnitOfMeasure.valueOf(unit) : null,
                datum.isNotBlank() ? Datum.valueOf(datum) : null)
```

2019-02-14 17:08 UTC, bakejeyner commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +    }
❓ Should this function be verifying that the next tag is the tag we are expecting (or log when we get a tag we don't expect)?

2019-02-14 17:08 UTC, bakejeyner commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/LinearRingTest.kt
> +                "</gml:LinearRing>"
✏️ Could use a raw string:
```
        val xml = """<gml:LinearRing xmlns:gml="http://www.opengis.net/gml">
                    |<gml:pos xmlns:gml="http://www.opengis.net/gml">0.0</gml:pos>
                    |<gml:pos xmlns:gml="http://www.opengis.net/gml">0.0</gml:pos>
                    |<gml:pos xmlns:gml="http://www.opengis.net/gml">0.0</gml:pos>
                    |<gml:pos xmlns:gml="http://www.opengis.net/gml">0.0</gml:pos>
                    |<gml:pos xmlns:gml="http://www.opengis.net/gml">0.0</gml:pos>
                    |</gml:LinearRing>""".trimMargin()
```

2019-02-14 17:08 UTC, bakejeyner commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/PointTest.kt
> +                "</gml:Point>"
✏️ Could use a raw string (example in first comment of this type)

2019-02-14 17:08 UTC, bakejeyner commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/PolygonTest.kt
> +                "</gml:LinearRing></gml:exterior></gml:Polygon>"
✏️ Could use a raw string (example in first comment of this type)

2019-02-14 17:08 UTC, bakejeyner commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/PositionTest.kt
> +        val xml = "<gml:pos srsName=\"wgs84\" xmlns:gml=\"http://www.opengis.net/gml\">0.0 0.0</gml:pos>"
✏️ Could use a raw string (example in first comment of this type)

2019-02-14 17:08 UTC, bakejeyner commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/SrsAttributesTest.kt
> +        val xml = "srsName=\"srsName\" srsDimension=\"2\" axisLabels=\"axis labels\" uomLabels=\"uom labels\""
✏️ Could use a raw string (example in first comment of this type)

2019-02-14 17:54 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/summary/TemporalCoverage.kt
> +)
That's a great idea. :+1:

2019-02-14 17:56 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +                if (datum.isNotBlank()) Datum.valueOf(datum) else null)
Sadly, Kotlin doesn't have a ternary operator, this is their suggested solution. :(

2019-02-14 21:12 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +    }
I made this tag so it would be clearer than the comments i had stating what the 'next' tag was. There are a few areas that `documentedTag` is a bunch of options that the tag could be like `person / organization / service`. I could change the name to fit better but not sure what it would be.

2019-02-14 21:19 UTC, coyotesqrl approved these changes

2019-02-14 21:28 UTC, AzGoalie commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/LinearRingTest.kt
> +                "</gml:LinearRing>"
We can't, the expected string doesn't have any new lines and the raw string adds them.

2019-02-14 21:28 UTC, AzGoalie commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/PointTest.kt
> +                "</gml:Point>"
We can't, the expected string doesn't have any new lines and the raw string adds them.

2019-02-14 21:28 UTC, AzGoalie commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/PolygonTest.kt
> +                "</gml:LinearRing></gml:exterior></gml:Polygon>"
We can't, the expected string doesn't have any new lines and the raw string adds them.

2019-02-14 21:29 UTC, AzGoalie commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/PositionTest.kt
> +        val xml = "<gml:pos srsName=\"wgs84\" xmlns:gml=\"http://www.opengis.net/gml\">0.0 0.0</gml:pos>"
Done

2019-02-14 21:30 UTC, AzGoalie commented on src/test/kotlin/org/codice/ddms/gml/v3/validation/SrsAttributesTest.kt
> +        val xml = "srsName=\"srsName\" srsDimension=\"2\" axisLabels=\"axis labels\" uomLabels=\"uom labels\""
Done

2019-02-15 21:46 UTC, brjeter commented on .gitattributes
> +# Set default behaviour, in case users don't have core.autocrlf set.
✏️ I think the README should probably be updated with more information. It's pretty bare right now. Some usage examples may be nice.

2019-02-15 21:46 UTC, brjeter commented on detekt.yml
> +    excludeImports: 'org.codice.compliance.SAMLSpecRefMessage.*,org.apache.cxf.rs.security.saml.sso.SSOConstants.*,java.util.*,kotlinx.android.synthetic.*'
✏️ I'm guessing you don't need some of these 😄

2019-02-15 21:46 UTC, brjeter commented on src/main/kotlin/org/codice/ddms/xml/util/XmlUtils.kt
> +    writeNamespace(prefix, uri)
❓ I'm confused about why these extension functions are necessary. Is it because you want to call `setPrefix` even if `prefix` is null or empty string?

2019-02-15 21:46 UTC, brjeter commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +        return reader.getAttributeValue(namespaceURI, localName) ?: ""
❓ Would it be overkill to trace log the attribute's `localName` here?

2019-02-15 21:46 UTC, brjeter commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +        while (localName != type) {
❓ This strikes me as a dangerous way to loop over this. Is there any likelihood that the DDMS could be malformed enough to cause this loop to execute more times than it should?

2019-02-15 21:46 UTC, brjeter commented on src/main/kotlin/org/codice/ddms/DdmsResource.kt
> +    val rights: Rights?
❓ Why are some of these fields nullable and some (e.g. `subjectCoverage`) aren't?

2019-02-15 21:46 UTC, brjeter commented on src/main/kotlin/org/codice/ddms/v2/builder/producers/OrganizationBuilder.kt
> +import org.codice.ddms.v2.resource.producers.Organization
✏️ Nit: It bothers me that there is parity between the builder package and corresponding "buildee" package for all except for this one, since the `producers` package is nested under `resource` in one but not the other.

2019-02-15 21:46 UTC, brjeter commented on .gitattributes
> +# Set default behaviour, in case users don't have core.autocrlf set.
Speaking of usage examples, it may be a good idea to have a test for this library in a Java class, just to make sure there are no interoperability snags.
I realize this is a decent amount of work, so it could be a future improvement. Just a thought.

2019-02-19 19:26 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/DdmsResource.kt
> +    val rights: Rights?
The nullable fields are fields that are optional in the DDMS spec.

2019-02-19 19:33 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/builder/producers/OrganizationBuilder.kt
> +import org.codice.ddms.v2.resource.producers.Organization
Good catch, moved.

2019-02-19 19:57 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/xml/util/XmlUtils.kt
> +    writeNamespace(prefix, uri)
When writing a namespace with `XMLStreamWriter` it excepts you to have already called `setPrefix`. This was just a helper extension method for calling `setPrefix` if it wasn't previously set.

2019-02-19 19:58 UTC, AzGoalie commented on src/main/kotlin/org/codice/ddms/v2/reader/Ddms20XmlReader.kt
> +        while (localName != type) {
If the XML is so malformed, it would read until the end of the file and then throw an exception. Not sure how we could change it.

2019-02-25 16:39 UTC, merged